"""Create ai_requests table

Revision ID: 7a1c33f9c0aa
Revises: 
Create Date: 2026-08-23 10:43:54.354076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1c33f9c0aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('doctors')
    op.drop_table('beds')
    op.drop_table('patients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('department_required', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('queue_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_wait_time_mins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('patients_pkey'))
    )
    op.create_table('beds',
    sa.Column('bed_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name=op.f('beds_patient_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('bed_id', name=op.f('beds_pkey'))
    )
    op.create_table('doctors',
    sa.Column('doctor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('doctor_id', name=op.f('doctors_pkey'))
    )
    op.drop_table('ai_requests')
    # ### end Alembic commands ###
