"""feat: add doctor availability tables

Revision ID: df92bf2469b3
Revises: 7a1c33f9c0aa
Create Date: 2026-08-25 23:22:28.693064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df92bf2469b3'
down_revision = '7a1c33f9c0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_specialization'), ['specialization'], unique=False)

    op.create_table('doctor_leaves',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_leaves_leave_date'), ['leave_date'], unique=False)

    op.create_table('doctor_schedules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_schedules')
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_leaves_leave_date'))

    op.drop_table('doctor_leaves')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_specialization'))

    op.drop_table('doctors')
    # ### end Alembic commands ###
